/* Lava Grill — full menu data, transcribed from the restaurant's printed menu. */
const MENU = [
  {
    id: 'appetizers',
    label: 'Appetizers',
    items: [
      { name: 'Samosa', desc: 'Chicken, beef, or veg', price: '$3.49' },
      { name: 'Cheese Sticks', desc: '6 pcs', price: '$4.79' },
      { name: 'Onion Rings', desc: '10 pcs', price: '$3.99' },
      { name: 'Small Fries', desc: '', price: '$3.49' },
      { name: 'Chicken Wrap', desc: 'Ranch, BBQ, or spicy BBQ', price: '$1.89' },
      { name: 'Garlic Bread', desc: '2 pcs', price: '$1.79' },
      { name: 'Desi Wrap', desc: 'Gyro wrap', price: '$1.89' },
      { name: 'Grilled Pita Bread', desc: '', price: '$1.49' },
      { name: 'Loaded Fries', desc: 'With chicken', price: '$6.99' },
      { name: 'Halim', desc: '', price: '$6.99' },
      { name: 'Piyaju', desc: '10 pcs', price: '$2.99' },
    ],
  },
  {
    id: 'ny-gyro',
    label: 'NY Style Gyro',
    note: 'Full tray $120',
    items: [
      { name: 'Lamb Gyro Rice', desc: 'NY style', price: '$8.99' },
      { name: 'Chicken Gyro Rice', desc: 'NY style', price: '$8.99' },
      { name: 'Mix Gyro Rice', desc: 'NY style', price: '$8.99' },
      { name: 'Philly Steak Gyro Rice', desc: 'NY style', price: '$10.99' },
    ],
  },
  {
    id: 'chicken',
    label: 'Chicken',
    items: [
      { name: 'Chicken Wings', desc: '6 pcs', price: '$7.99' },
      { name: 'Chicken Tenders', desc: '4 pcs, with fries', price: '$7.99' },
      { name: 'Chicken Nuggets', desc: '12 pcs, with fries', price: '$7.99' },
    ],
  },
  {
    id: 'salad',
    label: 'Salads',
    items: [
      { name: 'Grilled Chicken Salad', desc: '', price: '$5.99' },
      { name: 'Greek Salad', desc: '', price: '$5.99' },
      { name: 'Petus Salad', desc: '', price: '$4.99' },
    ],
  },
  {
    id: 'subs',
    label: 'Subs',
    items: [
      { name: 'Grilled Chicken Sub', desc: '', price: '$7.99' },
      { name: 'NY Style Lamb Gyro Sub', desc: '', price: '$7.99' },
      { name: 'Philly Cheese Steak', desc: 'Swiss, with fries', price: '$7.99' },
      { name: 'Spicy Grilled Chicken', desc: '', price: '$7.99' },
    ],
  },
  {
    id: 'mexican',
    label: 'Mexican',
    items: [
      { name: 'Grilled Chicken Quesadilla', desc: 'Served with sour cream', price: '$7.99' },
      { name: 'Lamb Gyro Quesadilla', desc: 'Served with sour cream', price: '$7.99' },
      { name: 'Cheese Quesadilla', desc: 'Served with sour cream', price: '$7.99' },
      { name: 'Philly Steak Quesadilla', desc: '', price: '$7.99' },
      { name: 'Chicken/Steak Pitadilla', desc: '', price: '$10.99' },
    ],
  },
  {
    id: 'pita',
    label: 'Pita Sandwiches',
    items: [
      { name: 'Gyro Sandwich', desc: 'Pita bread, with fries', price: '$7.99' },
      { name: 'Grilled Chicken Sandwich', desc: 'Pita bread, with fries', price: '$7.99' },
    ],
  },
  {
    id: 'desi-chinese',
    label: 'Desi Chinese',
    note: 'Full tray $120',
    items: [
      { name: 'Chicken-65', desc: 'With rice or noodles', price: '$9.99' },
      { name: 'Shrimp-65', desc: 'With rice or noodles', price: '$10.99' },
      { name: 'Mixed-65', desc: 'With rice or noodles', price: '$11.99' },
      { name: 'Sweet & Sour Chicken', desc: 'With rice or noodles', price: '$9.99' },
      { name: 'Sweet & Spicy Chicken', desc: 'With rice or noodles', price: '$9.99' },
      { name: 'Desi Chicken Fried Rice', desc: '', price: '$9.99' },
      { name: 'Shrimp Fried Rice', desc: '', price: '$9.99' },
      { name: '3-Way Fried Rice', desc: 'Shrimp, chicken & veg', price: '$10.99' },
      { name: 'Veggie Fried Rice', desc: '', price: '$9.99' },
      { name: 'Philly Steak Fried Rice', desc: '', price: '$10.99' },
      { name: 'Desi Special Fried Rice', desc: 'Shrimp, chicken, gyro & veg', price: '$11.99' },
    ],
  },
  {
    id: 'desi-special',
    label: 'Desi Specialties',
    note: 'Curry & biriyani',
    items: [
      { name: 'Chicken Curry', desc: '', price: '$9.99' },
      { name: 'Beef Curry', desc: '', price: '$10.99' },
      { name: 'Butter Chicken', desc: '', price: '$10.99' },
      { name: 'Roast Pulao', desc: '', price: 'Ask your server' },
      { name: 'Chicken Biriyani', desc: '', price: '$11.99' },
      { name: 'Beef Biriyani', desc: '', price: '$11.99' },
      { name: 'Lamb Biriyani', desc: '', price: '$12.99' },
      { name: 'Vegetable Biriyani', desc: '', price: '$8.99' },
      { name: 'Chicken 65 Biriyani', desc: '', price: '$11.99' },
      { name: 'Beef Tehari', desc: '', price: '$12.99' },
      { name: 'White Rice', desc: '', price: '$3.50' },
    ],
  },
  {
    id: 'lava-special',
    label: 'Lava Grill Specials',
    note: 'House favorites',
    items: [
      { name: 'Lava Special Jumbo Burger Combo', desc: 'Lettuce, tomato, 2 cheese, pickles, onions, 2 patties, mayo', price: '$10.99' },
      { name: 'Lava Special Chicken Burger Combo', desc: 'Lettuce, tomato, 2 cheese, pickles, onions, 2 patties — spicy or regular', price: '$9.99' },
      { name: 'Lava Grill Special Loaded Meat Box', desc: 'Chicken, lamb, corn, naan, sauce, cheese, chickpeas, wings, kebab, meatball, lava special sauce', price: '$13.99' },
      { name: 'Lava Special Naga Flavour', desc: 'Fiery house sauce', price: '$13.99' },
      { name: 'Lava Special Chicken Wings', desc: '6 pcs', price: '$4.99' },
      { name: 'Lava Special Fries Chicken', desc: '', price: '$7.99' },
      { name: 'Lava Grill Special Hamburger', desc: '', price: '$7.99' },
    ],
  },
  {
    id: 'extras',
    label: 'Extras',
    items: [
      { name: 'Extra Rice', desc: '', price: '$1.99' },
      { name: 'Extra Gyro', desc: '', price: '$1.99' },
      { name: 'Extra Cheese', desc: '', price: '$1.99' },
      { name: 'Extra White/Red Sauce', desc: '', price: '$0.79' },
      { name: 'Extra Fries', desc: '', price: '$1.99' },
    ],
  },
  {
    id: 'desserts',
    label: 'Desserts',
    items: [
      { name: 'Mango Sticky Rice', desc: '', price: '$9.99' },
      { name: 'Rice Pudding', desc: '', price: '$2.99' },
      { name: 'Tiramisu', desc: '', price: '$3.49' },
      { name: "Hershey's Pie", desc: '', price: '$3.50' },
    ],
  },
  {
    id: 'beverages',
    label: 'Beverages',
    items: [
      { name: 'Soft Drinks', desc: '', price: '$1.50' },
      { name: 'Desi Tea', desc: '', price: '$1.50' },
      { name: 'Mango Shake', desc: '', price: '$4.99' },
      { name: 'Water Bottle', desc: '', price: '$1.50' },
    ],
  },
];
